spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.4:3306/bootstudy
    name: mysql_hp_bootstudy
#    type: com.alibaba.druid.pool.DruidDataSource # 使用druid 数据源
mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mapper/*.xml
